{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kutear.gm-library",
    "module": "gm-ext-webview",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "gm-ext-webview-0.0.1-SNAPSHOT.aar",
          "url": "gm-ext-webview-0.0.1-SNAPSHOT.aar",
          "size": 38569,
          "sha512": "529ea23ec2fc8a6c589a8f15e92498a2f5880305f87ef5834de107fa6859d6fa81a6072e8cea9ad6cd7a8ea37e62f34e003af88ed5a0d17622a77d66185e68c1",
          "sha256": "e82431c80c4f1ca01d5e8336cb8ed3f891a8e7e3967ba1a83f2127cc6e4bbbc0",
          "sha1": "fdeda7c84f15b77410a6cb5f5ac47ad00fcd0225",
          "md5": "ede9654113ec4704774aa0cea837b854"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.kutear.gm-library",
          "module": "gm-core",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "gm-ext-webview-0.0.1-SNAPSHOT.aar",
          "url": "gm-ext-webview-0.0.1-SNAPSHOT.aar",
          "size": 38569,
          "sha512": "529ea23ec2fc8a6c589a8f15e92498a2f5880305f87ef5834de107fa6859d6fa81a6072e8cea9ad6cd7a8ea37e62f34e003af88ed5a0d17622a77d66185e68c1",
          "sha256": "e82431c80c4f1ca01d5e8336cb8ed3f891a8e7e3967ba1a83f2127cc6e4bbbc0",
          "sha1": "fdeda7c84f15b77410a6cb5f5ac47ad00fcd0225",
          "md5": "ede9654113ec4704774aa0cea837b854"
        }
      ]
    }
  ]
}
