{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kutear.gm-library",
    "module": "gm-ext-webview",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "gm-ext-webview-0.0.1.aar",
          "url": "gm-ext-webview-0.0.1.aar",
          "size": 38377,
          "sha512": "0141b2ca9a4a751b4399fa1f01ced971d8402f268c7d2cc4f68c3c6c4fa64c329f3632f773d27b6faadabea973bc40d43389032fc469ba224667f10e7d89ae49",
          "sha256": "acb23bb49e02fdf2fe085dce2ab21e5bf7474ff19d9863c8d31766d665720e66",
          "sha1": "e0339fdfea201183ead473fda4056b2df738710a",
          "md5": "81e87056dd3606a75a923c8eb690288f"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.kutear.gm-library",
          "module": "gm-core",
          "version": {
            "requires": "0.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "gm-ext-webview-0.0.1.aar",
          "url": "gm-ext-webview-0.0.1.aar",
          "size": 38377,
          "sha512": "0141b2ca9a4a751b4399fa1f01ced971d8402f268c7d2cc4f68c3c6c4fa64c329f3632f773d27b6faadabea973bc40d43389032fc469ba224667f10e7d89ae49",
          "sha256": "acb23bb49e02fdf2fe085dce2ab21e5bf7474ff19d9863c8d31766d665720e66",
          "sha1": "e0339fdfea201183ead473fda4056b2df738710a",
          "md5": "81e87056dd3606a75a923c8eb690288f"
        }
      ]
    }
  ]
}
