{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kutear.gm-library",
    "module": "gm-core",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxandroid",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "gm-core-0.0.1-SNAPSHOT.aar",
          "url": "gm-core-0.0.1-SNAPSHOT.aar",
          "size": 92679,
          "sha512": "de14c8abcc0997d694441e2da99d0e3f44675b6f7fce2847cf09afd427a25b9d65d9d223cbf8b5d61c53d50929d84614b9db6ace50532afc57c3c24c012f0d44",
          "sha256": "3483c18db1ebe2539d7d2349c44e3050e351597756a37e5cb13d7e4e121b87e3",
          "sha1": "a51a13926f3136c9ce10be6b5b774b2536cdc802",
          "md5": "90667d5293e7b22c6519a90bccf45bfe"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxandroid",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "gm-core-0.0.1-SNAPSHOT.aar",
          "url": "gm-core-0.0.1-SNAPSHOT.aar",
          "size": 92679,
          "sha512": "de14c8abcc0997d694441e2da99d0e3f44675b6f7fce2847cf09afd427a25b9d65d9d223cbf8b5d61c53d50929d84614b9db6ace50532afc57c3c24c012f0d44",
          "sha256": "3483c18db1ebe2539d7d2349c44e3050e351597756a37e5cb13d7e4e121b87e3",
          "sha1": "a51a13926f3136c9ce10be6b5b774b2536cdc802",
          "md5": "90667d5293e7b22c6519a90bccf45bfe"
        }
      ]
    }
  ]
}
